name: Java CI
on: [push, pull_request]
jobs:
	build-test:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- uses: actions/setup-java@v4
			  with:
				  distribution: temurin
				  java-version: '17'
				  cache: maven
			- name: Build & Test
			  run: mvn -B clean test
			- name: Publicar reporte Surefire
			  if: always()
			  uses: actions/upload-artifact@v4
			  with:
				  name: surefire-reports
				  path: target/surefire-reportsurefire-reports